/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    /** Register */
    post: operations["register_auth_register_post"];
  };
  "/auth/login": {
    /** Login */
    post: operations["login_auth_login_post"];
  };
  "/auth/refresh": {
    /**
     * Refresh Token
     * @description Exchange a valid refresh token for a new access token.
     * The refresh token is rotated on every use.
     */
    post: operations["refresh_token_auth_refresh_post"];
  };
  "/auth/logout": {
    /**
     * Logout
     * @description Invalidate both the refresh token (Redis delete) and the current access
     * token (jti blocklist, expiring when the token would have expired naturally).
     * After this returns, the access token is unusable even within its 15-min window.
     */
    post: operations["logout_auth_logout_post"];
  };
  "/auth/me": {
    /** Me */
    get: operations["me_auth_me_get"];
    /**
     * Update Profile
     * @description Update mutable profile fields. Only provided (non-None) fields are changed.
     */
    patch: operations["update_profile_auth_me_patch"];
  };
  "/auth/check-username": {
    /**
     * Check Username
     * @description Real-time uniqueness check for use during signup.
     * Returns {"available": true} when the username is valid and not yet taken.
     * No authentication required — called as the user types.
     * Rate-limited by the API gateway / Nginx upstream.
     */
    get: operations["check_username_auth_check_username_get"];
  };
  "/accounts/manual": {
    /**
     * Add Manual Account
     * @description Create a manual bank account.
     *
     * The alias field is the user-facing display name and is always editable.
     * account_name mirrors alias on creation and can be updated independently.
     */
    post: operations["add_manual_account_accounts_manual_post"];
  };
  "/accounts": {
    /** List Accounts */
    get: operations["list_accounts_accounts_get"];
  };
  "/accounts/{account_id}/alias": {
    /**
     * Update Alias
     * @description Update the display alias for any account (manual or linked).
     */
    patch: operations["update_alias_accounts__account_id__alias_patch"];
  };
  "/accounts/{account_id}/balance": {
    /**
     * Update Manual Balance
     * @description Update the balance of a manual account and append an audit entry.
     */
    patch: operations["update_manual_balance_accounts__account_id__balance_patch"];
  };
  "/accounts/{account_id}": {
    /**
     * Delete Account
     * @description Soft-delete an account. Transaction history is preserved.
     */
    delete: operations["delete_account_accounts__account_id__delete"];
  };
  "/transactions": {
    /** List Transactions */
    get: operations["list_transactions_transactions_get"];
  };
  "/transactions/{tx_id}": {
    /** Get Transaction */
    get: operations["get_transaction_transactions__tx_id__get"];
    /**
     * Delete Transaction
     * @description Delete a transaction.
     */
    delete: operations["delete_transaction_transactions__tx_id__delete"];
    /**
     * Patch Transaction
     * @description Patch a transaction. All fields are editable by the owner.
     *
     * Budget activity is recalculated atomically — one undo of the old state,
     * one application of the new state — to avoid double-counting when amount,
     * type, date, and/or category change in the same request.
     */
    patch: operations["patch_transaction_transactions__tx_id__patch"];
  };
  "/transactions/{tx_id}/split": {
    /**
     * Split Transaction
     * @description Replace this transaction's category assignment with 2+ split assignments.
     * The split amounts must sum to ABS(transaction.amount).
     */
    post: operations["split_transaction_transactions__tx_id__split_post"];
    /**
     * Remove Split
     * @description Remove all splits, reverting the transaction to uncategorized.
     */
    delete: operations["remove_split_transactions__tx_id__split_delete"];
  };
  "/transactions/manual": {
    /**
     * Create Manual Transaction
     * @description Create a transaction entered manually by the user.
     */
    post: operations["create_manual_transaction_transactions_manual_post"];
  };
  "/budget": {
    /**
     * Get Budget
     * @description Full budget view for a month:
     * all groups → categories with assigned / activity / available / required_this_month,
     * plus the global TBB.
     */
    get: operations["get_budget_budget_get"];
  };
  "/budget/{category_id}": {
    /**
     * Set Assignment
     * @description Set (replace) the assigned amount for a category in a month.
     */
    patch: operations["set_assignment_budget__category_id__patch"];
  };
  "/budget/move": {
    /**
     * Move Money
     * @description Atomically move kobo from one category to another within the same month.
     * Decrements assigned on source, increments on destination.
     */
    post: operations["move_money_budget_move_post"];
  };
  "/budget/tbb": {
    /** Get Tbb */
    get: operations["get_tbb_budget_tbb_get"];
  };
  "/budget/underfunded": {
    /**
     * List Underfunded
     * @description Return categories where available < required_this_month.
     */
    get: operations["list_underfunded_budget_underfunded_get"];
  };
  "/budget/auto-assign": {
    /**
     * Auto Assign
     * @description Bulk-assign categories for a month using one of five strategies:
     *
     * - **underfunded**          Fill categories behind their targets.
     *                            Respects target-type priority order and stops
     *                            when TBB reaches zero (TBB-capped).
     * - **assigned_last_month**  Mirror each category's assigned amount from
     *                            the previous calendar month.
     * - **spent_last_month**     Assign what was actually spent last month
     *                            (abs of activity).
     * - **avg_assigned**         3-month average of past assigned amounts
     *                            (non-zero months only, ceiling-rounded).
     * - **avg_spent**            3-month average of past spending amounts
     *                            (non-zero months only, ceiling-rounded).
     *
     * Historical strategies do **not** clamp to TBB; TBB may go negative.
     */
    post: operations["auto_assign_budget_auto_assign_post"];
  };
  "/categories": {
    /**
     * List Categories
     * @description Return all category groups with their nested categories.
     */
    get: operations["list_categories_categories_get"];
    /** Create Category */
    post: operations["create_category_categories_post"];
  };
  "/categories/{category_id}": {
    /**
     * Delete Category
     * @description Delete a category if it has no transactions. Otherwise hide it.
     */
    delete: operations["delete_category_categories__category_id__delete"];
    /** Update Category */
    patch: operations["update_category_categories__category_id__patch"];
  };
  "/categories/{category_id}/sort": {
    /** Sort Category */
    patch: operations["sort_category_categories__category_id__sort_patch"];
  };
  "/categories/{category_id}/target": {
    /** Get Target */
    get: operations["get_target_categories__category_id__target_get"];
    /** Upsert Target */
    put: operations["upsert_target_categories__category_id__target_put"];
    /** Delete Target */
    delete: operations["delete_target_categories__category_id__target_delete"];
  };
  "/category-groups": {
    /** List Groups */
    get: operations["list_groups_category_groups_get"];
    /** Create Group */
    post: operations["create_group_category_groups_post"];
  };
  "/category-groups/{group_id}": {
    /**
     * Delete Group
     * @description Delete a group only if it has no categories.
     * If it has categories, archive it (is_hidden=True) instead.
     */
    delete: operations["delete_group_category_groups__group_id__delete"];
    /** Update Group */
    patch: operations["update_group_category_groups__group_id__patch"];
  };
  "/category-groups/{group_id}/sort": {
    /** Sort Group */
    patch: operations["sort_group_category_groups__group_id__sort_patch"];
  };
  "/nudges": {
    /**
     * List nudges
     * @description Returns the user's nudges sorted by creation time (newest first).
     * Undismissed nudges always sort before dismissed ones.
     *
     * unread_count: delivered nudges not yet opened and not dismissed.
     */
    get: operations["list_nudges_nudges_get"];
  };
  "/nudges/settings": {
    /** Get nudge settings */
    get: operations["get_settings_nudges_settings_get"];
    /** Update nudge settings */
    patch: operations["update_settings_nudges_settings_patch"];
  };
  "/nudges/{nudge_id}": {
    /** Get a single nudge */
    get: operations["get_nudge_nudges__nudge_id__get"];
    /** Delete a nudge */
    delete: operations["delete_nudge_nudges__nudge_id__delete"];
  };
  "/nudges/{nudge_id}/open": {
    /** Mark nudge as opened */
    post: operations["open_nudge_nudges__nudge_id__open_post"];
  };
  "/nudges/{nudge_id}/dismiss": {
    /** Dismiss a nudge */
    post: operations["dismiss_nudge_nudges__nudge_id__dismiss_post"];
  };
  "/nudges/mark-all-read": {
    /** Mark all nudges as opened */
    post: operations["mark_all_read_nudges_mark_all_read_post"];
  };
  "/nudges/register-device": {
    /**
     * Register push notification token
     * @description Store the device's push token so the backend can deliver push notifications.
     *
     * Accepts:
     *   - Expo push tokens: "ExponentPushToken[xxxxxx]"  (development + Expo Go)
     *
     * Idempotent — re-registering the same token is safe.
     */
    post: operations["register_device_nudges_register_device_post"];
  };
  "/nudges/test-trigger": {
    /**
     * Create a synthetic nudge for testing
     * @description Creates a realistic synthetic nudge for the given trigger_type. Bypasses fatigue and dedup checks. Safe in all environments.
     */
    post: operations["test_trigger_nudges_test_trigger_post"];
  };
  "/sync/pull": {
    /**
     * Pull
     * @description Return all records created or updated since last_pulled_at.
     * Runs lazy recurring-transaction generation before querying.
     * Scoped to the authenticated user.
     */
    get: operations["pull_sync_pull_get"];
  };
  "/sync/push": {
    /**
     * Push
     * @description Process client-side writes for all six WatermelonDB tables.
     * Rate-limited to 60 pushes per user per minute.
     */
    post: operations["push_sync_push_post"];
  };
  "/webhooks/bank-alerts": {
    /**
     * Bank Alert Webhook
     * @description Receives parsed bank-alert emails forwarded by the Cloudflare email-worker.
     *
     * Security: constant-time comparison against BANK_ALERT_WEBHOOK_SECRET.
     * The endpoint returns 403 (not 401) to avoid leaking auth scheme details.
     *
     * Payload shape (set by the email-worker):
     *     { "to": str, "from": str, "subject": str|null, "body": str|null, "html": str|null }
     *
     * Processing pipeline:
     *     1. Verify shared secret.
     *     2. Parse body → ParsedBankAlert.
     *     3. Resolve recipient username → User.
     *     4. Resolve institution → BankAccount.
     *     5. Deduplicate via external_ref.
     *     6. Insert Transaction row.
     *     7. Update BankAccount.last_synced_at.
     *     8. Enqueue categorize_transactions Celery task.
     *     9. Notify user via WebSocket.
     */
    post: operations["bank_alert_webhook_webhooks_bank_alerts_post"];
  };
  "/recurring-rules": {
    /**
     * List Rules
     * @description Return all active recurring rules for the current user.
     */
    get: operations["list_rules_recurring_rules_get"];
    /**
     * Create Rule
     * @description Create a new recurring rule. The first occurrence is generated lazily on the next sync.
     */
    post: operations["create_rule_recurring_rules_post"];
  };
  "/recurring-rules/{rule_id}": {
    /** Get Rule */
    get: operations["get_rule_recurring_rules__rule_id__get"];
    /**
     * Delete Rule
     * @description Hard-delete a recurring rule. Past transactions generated by this rule are preserved.
     */
    delete: operations["delete_rule_recurring_rules__rule_id__delete"];
    /**
     * Update Rule
     * @description Update is_active, ends_on, or next_due. Set is_active=false to pause / stop the rule.
     */
    patch: operations["update_rule_recurring_rules__rule_id__patch"];
  };
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AccessTokenResponse */
    AccessTokenResponse: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
    };
    /** AddManualAccountRequest */
    AddManualAccountRequest: {
      /** Institution */
      institution: string;
      /** Account Number */
      account_number: string;
      /** Alias */
      alias: string;
      /**
       * Account Type
       * @default SAVINGS
       */
      account_type?: string;
      /**
       * Currency
       * @default NGN
       */
      currency?: string;
      /**
       * Balance
       * @default 0
       */
      balance?: number;
    };
    /** AssignRequest */
    AssignRequest: {
      /** Assigned */
      assigned: number;
    };
    /** AutoAssignResponse */
    AutoAssignResponse: {
      /** Month */
      month: string;
      strategy: components["schemas"]["AutoAssignStrategy"];
      /** Assignments Made */
      assignments_made: number;
      /** Total Assigned */
      total_assigned: number;
      /** Still Underfunded */
      still_underfunded: string[];
    };
    /**
     * AutoAssignStrategy
     * @enum {string}
     */
    AutoAssignStrategy: "underfunded" | "assigned_last_month" | "spent_last_month" | "avg_assigned" | "avg_spent";
    /** BankAccountResponse */
    BankAccountResponse: {
      /** Id */
      id: string;
      /** Institution */
      institution: string;
      /** Account Name */
      account_name: string;
      /** Alias */
      alias?: string | null;
      /** Account Number */
      account_number?: string | null;
      /** Account Type */
      account_type: string;
      /** Currency */
      currency: string;
      /** Balance */
      balance: number;
      /** Balance As Of */
      balance_as_of?: string | null;
      /** Last Synced At */
      last_synced_at?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Deleted At */
      deleted_at?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** BudgetCategoryResponse */
    BudgetCategoryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order: number;
      /** Is Hidden */
      is_hidden: boolean;
      /** Assigned */
      assigned: number;
      /** Activity */
      activity: number;
      /** Available */
      available: number;
      /** Required This Month */
      required_this_month: number | null;
      /** Target Amount */
      target_amount: number | null;
      /** Target Frequency */
      target_frequency: string | null;
      /** Target Behavior */
      target_behavior: string | null;
      /** Target Date */
      target_date: string | null;
    };
    /** BudgetGroupResponse */
    BudgetGroupResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order: number;
      /** Is Hidden */
      is_hidden: boolean;
      /** Categories */
      categories: components["schemas"]["BudgetCategoryResponse"][];
    };
    /** BudgetResponse */
    BudgetResponse: {
      /** Month */
      month: string;
      /** Tbb */
      tbb: number;
      /** Groups */
      groups: components["schemas"]["BudgetGroupResponse"][];
      /**
       * Total Debit
       * @default 0
       */
      total_debit?: number;
    };
    /** CategoryCreate */
    CategoryCreate: {
      /**
       * Group Id
       * Format: uuid
       */
      group_id: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order?: number | null;
    };
    /** CategoryGroupCreate */
    CategoryGroupCreate: {
      /** Name */
      name: string;
      /** Sort Order */
      sort_order?: number | null;
    };
    /** CategoryGroupResponse */
    CategoryGroupResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order: number;
      /** Is Hidden */
      is_hidden: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** CategoryGroupUpdate */
    CategoryGroupUpdate: {
      /** Name */
      name?: string | null;
      /** Sort Order */
      sort_order?: number | null;
      /** Is Hidden */
      is_hidden?: boolean | null;
    };
    /**
     * CategoryGroupWithCategories
     * @description Category group with its nested categories — used in budget and category list responses.
     */
    CategoryGroupWithCategories: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order: number;
      /** Is Hidden */
      is_hidden: boolean;
      /** Categories */
      categories: components["schemas"]["CategoryResponse"][];
    };
    /** CategoryResponse */
    CategoryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Group Id
       * Format: uuid
       */
      group_id: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order: number;
      /** Is Hidden */
      is_hidden: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** CategoryTargetResponse */
    CategoryTargetResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      frequency: components["schemas"]["TargetFrequency"];
      behavior: components["schemas"]["TargetBehavior"];
      /** Target Amount */
      target_amount: number;
      /** Day Of Week */
      day_of_week: number | null;
      /** Day Of Month */
      day_of_month: number | null;
      /** Target Date */
      target_date: string | null;
      /** Repeats */
      repeats: boolean;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CategoryTargetUpsert */
    CategoryTargetUpsert: {
      frequency: components["schemas"]["TargetFrequency"];
      /** @default set_aside */
      behavior?: components["schemas"]["TargetBehavior"];
      /** Target Amount */
      target_amount: number;
      /** Day Of Week */
      day_of_week?: number | null;
      /** Day Of Month */
      day_of_month?: number | null;
      /** Target Date */
      target_date?: string | null;
      /**
       * Repeats
       * @default false
       */
      repeats?: boolean;
    };
    /** CategoryUpdate */
    CategoryUpdate: {
      /** Name */
      name?: string | null;
      /** Group Id */
      group_id?: string | null;
      /** Sort Order */
      sort_order?: number | null;
      /** Is Hidden */
      is_hidden?: boolean | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** ManualTransactionRequest */
    ManualTransactionRequest: {
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /**
       * Date
       * Format: date-time
       */
      date: string;
      /** Amount */
      amount: number;
      /** Narration */
      narration: string;
      /**
       * Type
       * @enum {string}
       */
      type: "debit" | "credit";
      /** Category Id */
      category_id?: string | null;
      /** Memo */
      memo?: string | null;
    };
    /** MoveMoneyRequest */
    MoveMoneyRequest: {
      /**
       * From Category Id
       * Format: uuid
       */
      from_category_id: string;
      /**
       * To Category Id
       * Format: uuid
       */
      to_category_id: string;
      /** Amount */
      amount: number;
      /** Month */
      month: string;
    };
    /** NudgeListResponse */
    NudgeListResponse: {
      /** Nudges */
      nudges: components["schemas"]["NudgeResponse"][];
      /** Total */
      total: number;
      /** Unread Count */
      unread_count: number;
    };
    /** NudgeResponse */
    NudgeResponse: {
      /** Id */
      id: string;
      trigger_type: components["schemas"]["NudgeTriggerType"];
      /** Title */
      title: string | null;
      /** Message */
      message: string;
      /** Context */
      context?: {
        [key: string]: unknown;
      } | null;
      /** Category Id */
      category_id?: string | null;
      /** Is Opened */
      is_opened: boolean;
      /** Is Dismissed */
      is_dismissed: boolean;
      /** Delivered At */
      delivered_at?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** NudgeSettingsResponse */
    NudgeSettingsResponse: {
      /** Enabled */
      enabled: boolean;
      /** Quiet Hours Start */
      quiet_hours_start: string;
      /** Quiet Hours End */
      quiet_hours_end: string;
      /** Fatigue Limit */
      fatigue_limit: number;
      /** Language */
      language: string;
    };
    /** NudgeSettingsUpdate */
    NudgeSettingsUpdate: {
      /** Enabled */
      enabled?: boolean | null;
      /**
       * Quiet Hours Start
       * @description HH:MM format, e.g. '23:00'
       */
      quiet_hours_start?: string | null;
      /**
       * Quiet Hours End
       * @description HH:MM format, e.g. '07:00'
       */
      quiet_hours_end?: string | null;
      /** Fatigue Limit */
      fatigue_limit?: number | null;
      /** Language */
      language?: string | null;
    };
    /**
     * NudgeTriggerType
     * @enum {string}
     */
    NudgeTriggerType: "threshold_80" | "threshold_100" | "large_single_tx" | "pay_received" | "bill_payment";
    /** RecurringRuleCreate */
    RecurringRuleCreate: {
      /**
       * Frequency
       * @enum {string}
       */
      frequency: "daily" | "weekly" | "biweekly" | "monthly" | "yearly" | "custom";
      /**
       * Interval
       * @default 1
       */
      interval?: number;
      /** Day Of Week */
      day_of_week?: number | null;
      /** Day Of Month */
      day_of_month?: number | null;
      /**
       * Next Due
       * Format: date
       */
      next_due: string;
      /** Ends On */
      ends_on?: string | null;
      template: components["schemas"]["RecurringTemplate"];
    };
    /** RecurringRuleResponse */
    RecurringRuleResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Frequency
       * @enum {string}
       */
      frequency: "daily" | "weekly" | "biweekly" | "monthly" | "yearly" | "custom";
      /** Interval */
      interval: number;
      /** Day Of Week */
      day_of_week: number | null;
      /** Day Of Month */
      day_of_month: number | null;
      /**
       * Next Due
       * Format: date
       */
      next_due: string;
      /** Ends On */
      ends_on: string | null;
      /** Is Active */
      is_active: boolean;
      template: components["schemas"]["RecurringTemplate"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * RecurringRuleUpdate
     * @description All fields optional — only provided fields are updated.
     */
    RecurringRuleUpdate: {
      /** Is Active */
      is_active?: boolean | null;
      /** Ends On */
      ends_on?: string | null;
      /** Next Due */
      next_due?: string | null;
    };
    /** RecurringTemplate */
    RecurringTemplate: {
      /** Account Id */
      account_id: string;
      /** Amount */
      amount: number;
      /** Narration */
      narration: string;
      /**
       * Type
       * @enum {string}
       */
      type: "debit" | "credit";
      /** Category Id */
      category_id?: string | null;
      /** Memo */
      memo?: string | null;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** RegisterDeviceRequest */
    RegisterDeviceRequest: {
      /**
       * Token
       * @description Expo push token ('ExponentPushToken[...]')
       */
      token: string;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Username */
      username: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Phone */
      phone?: string | null;
    };
    /** TBBResponse */
    TBBResponse: {
      /** Month */
      month: string;
      /** Tbb */
      tbb: number;
    };
    /**
     * TargetBehavior
     * @enum {string}
     */
    TargetBehavior: "set_aside" | "refill" | "balance";
    /**
     * TargetFrequency
     * @enum {string}
     */
    TargetFrequency: "weekly" | "monthly" | "yearly" | "custom";
    /** TestTriggerRequest */
    TestTriggerRequest: {
      trigger_type: components["schemas"]["NudgeTriggerType"];
      /** Category Id */
      category_id?: string | null;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
    };
    /** TransactionListResponse */
    TransactionListResponse: {
      /** Items */
      items: components["schemas"]["TransactionResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Limit */
      limit: number;
    };
    /**
     * TransactionPatchRequest
     * @description Patch a transaction.  All fields are editable regardless of source.
     */
    TransactionPatchRequest: {
      /** Category Id */
      category_id?: string | null;
      /** Memo */
      memo?: string | null;
      /** Type */
      type?: ("debit" | "credit") | null;
      /** Amount */
      amount?: number | null;
      /** Narration */
      narration?: string | null;
      /** Date */
      date?: string | null;
      /** Account Id */
      account_id?: string | null;
    };
    /** TransactionResponse */
    TransactionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /**
       * Date
       * Format: date-time
       */
      date: string;
      /** Amount */
      amount: number;
      /** Narration */
      narration: string;
      /** Type */
      type: string;
      /** Balance After */
      balance_after: number | null;
      /** Category Id */
      category_id: string | null;
      /** Memo */
      memo: string | null;
      /** Is Split */
      is_split: boolean;
      source: components["schemas"]["TransactionSource"];
      /** Recurrence Id */
      recurrence_id: string | null;
      /** Splits */
      splits: components["schemas"]["TransactionSplitResponse"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * TransactionSource
     * @enum {string}
     */
    TransactionSource: "bank_alert" | "manual";
    /** TransactionSplitItem */
    TransactionSplitItem: {
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Amount */
      amount: number;
      /** Memo */
      memo?: string | null;
    };
    /** TransactionSplitRequest */
    TransactionSplitRequest: {
      /** Splits */
      splits: components["schemas"]["TransactionSplitItem"][];
    };
    /** TransactionSplitResponse */
    TransactionSplitResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Category Id */
      category_id: string | null;
      /** Amount */
      amount: number;
      /** Memo */
      memo: string | null;
    };
    /** UnderfundedCategoryResponse */
    UnderfundedCategoryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Available */
      available: number;
      /** Required This Month */
      required_this_month: number;
      /** Shortfall */
      shortfall: number;
    };
    /** UpdateAliasRequest */
    UpdateAliasRequest: {
      /** Alias */
      alias: string;
    };
    /** UpdateManualBalanceRequest */
    UpdateManualBalanceRequest: {
      /**
       * Balance
       * @description New balance in kobo
       */
      balance: number;
      /** Note */
      note?: string | null;
    };
    /** UpdateProfileRequest */
    UpdateProfileRequest: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Onboarded */
      onboarded?: boolean | null;
      /** Username */
      username?: string | null;
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: string;
      /** Email */
      email: string;
      /** Username */
      username: string | null;
      /** First Name */
      first_name: string | null;
      /** Last Name */
      last_name: string | null;
      /** Phone */
      phone: string | null;
      /** Identity Verified */
      identity_verified: boolean;
      /** Onboarded */
      onboarded: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Register */
  register_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Refresh Token
   * @description Exchange a valid refresh token for a new access token.
   * The refresh token is rotated on every use.
   */
  refresh_token_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Logout
   * @description Invalidate both the refresh token (Redis delete) and the current access
   * token (jti blocklist, expiring when the token would have expired naturally).
   * After this returns, the access token is unusable even within its 15-min window.
   */
  logout_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /** Me */
  me_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /**
   * Update Profile
   * @description Update mutable profile fields. Only provided (non-None) fields are changed.
   */
  update_profile_auth_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Check Username
   * @description Real-time uniqueness check for use during signup.
   * Returns {"available": true} when the username is valid and not yet taken.
   * No authentication required — called as the user types.
   * Rate-limited by the API gateway / Nginx upstream.
   */
  check_username_auth_check_username_get: {
    parameters: {
      query: {
        username: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Add Manual Account
   * @description Create a manual bank account.
   *
   * The alias field is the user-facing display name and is always editable.
   * account_name mirrors alias on creation and can be updated independently.
   */
  add_manual_account_accounts_manual_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddManualAccountRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["BankAccountResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Accounts */
  list_accounts_accounts_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BankAccountResponse"][];
        };
      };
    };
  };
  /**
   * Update Alias
   * @description Update the display alias for any account (manual or linked).
   */
  update_alias_accounts__account_id__alias_patch: {
    parameters: {
      path: {
        account_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAliasRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BankAccountResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Manual Balance
   * @description Update the balance of a manual account and append an audit entry.
   */
  update_manual_balance_accounts__account_id__balance_patch: {
    parameters: {
      path: {
        account_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateManualBalanceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BankAccountResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Account
   * @description Soft-delete an account. Transaction history is preserved.
   */
  delete_account_accounts__account_id__delete: {
    parameters: {
      path: {
        account_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Transactions */
  list_transactions_transactions_get: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        account_id?: string | null;
        category_id?: string | null;
        /** @description YYYY-MM-DD */
        start_date?: string | null;
        /** @description YYYY-MM-DD */
        end_date?: string | null;
        uncategorized?: boolean | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Transaction */
  get_transaction_transactions__tx_id__get: {
    parameters: {
      path: {
        tx_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Transaction
   * @description Delete a transaction.
   */
  delete_transaction_transactions__tx_id__delete: {
    parameters: {
      path: {
        tx_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Patch Transaction
   * @description Patch a transaction. All fields are editable by the owner.
   *
   * Budget activity is recalculated atomically — one undo of the old state,
   * one application of the new state — to avoid double-counting when amount,
   * type, date, and/or category change in the same request.
   */
  patch_transaction_transactions__tx_id__patch: {
    parameters: {
      path: {
        tx_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransactionPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Split Transaction
   * @description Replace this transaction's category assignment with 2+ split assignments.
   * The split amounts must sum to ABS(transaction.amount).
   */
  split_transaction_transactions__tx_id__split_post: {
    parameters: {
      path: {
        tx_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransactionSplitRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Remove Split
   * @description Remove all splits, reverting the transaction to uncategorized.
   */
  remove_split_transactions__tx_id__split_delete: {
    parameters: {
      path: {
        tx_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Manual Transaction
   * @description Create a transaction entered manually by the user.
   */
  create_manual_transaction_transactions_manual_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManualTransactionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Budget
   * @description Full budget view for a month:
   * all groups → categories with assigned / activity / available / required_this_month,
   * plus the global TBB.
   */
  get_budget_budget_get: {
    parameters: {
      query?: {
        /** @description YYYY-MM */
        month?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BudgetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Set Assignment
   * @description Set (replace) the assigned amount for a category in a month.
   */
  set_assignment_budget__category_id__patch: {
    parameters: {
      query?: {
        /** @description YYYY-MM */
        month?: string | null;
      };
      path: {
        category_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BudgetCategoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Move Money
   * @description Atomically move kobo from one category to another within the same month.
   * Decrements assigned on source, increments on destination.
   */
  move_money_budget_move_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveMoneyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Tbb */
  get_tbb_budget_tbb_get: {
    parameters: {
      query?: {
        /** @description YYYY-MM */
        month?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TBBResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Underfunded
   * @description Return categories where available < required_this_month.
   */
  list_underfunded_budget_underfunded_get: {
    parameters: {
      query?: {
        /** @description YYYY-MM */
        month?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UnderfundedCategoryResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Auto Assign
   * @description Bulk-assign categories for a month using one of five strategies:
   *
   * - **underfunded**          Fill categories behind their targets.
   *                            Respects target-type priority order and stops
   *                            when TBB reaches zero (TBB-capped).
   * - **assigned_last_month**  Mirror each category's assigned amount from
   *                            the previous calendar month.
   * - **spent_last_month**     Assign what was actually spent last month
   *                            (abs of activity).
   * - **avg_assigned**         3-month average of past assigned amounts
   *                            (non-zero months only, ceiling-rounded).
   * - **avg_spent**            3-month average of past spending amounts
   *                            (non-zero months only, ceiling-rounded).
   *
   * Historical strategies do **not** clamp to TBB; TBB may go negative.
   */
  auto_assign_budget_auto_assign_post: {
    parameters: {
      query?: {
        /** @description Assignment strategy to apply */
        strategy?: components["schemas"]["AutoAssignStrategy"];
        /** @description YYYY-MM */
        month?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AutoAssignResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Categories
   * @description Return all category groups with their nested categories.
   */
  list_categories_categories_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryGroupWithCategories"][];
        };
      };
    };
  };
  /** Create Category */
  create_category_categories_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Category
   * @description Delete a category if it has no transactions. Otherwise hide it.
   */
  delete_category_categories__category_id__delete: {
    parameters: {
      path: {
        category_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Category */
  update_category_categories__category_id__patch: {
    parameters: {
      path: {
        category_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Sort Category */
  sort_category_categories__category_id__sort_patch: {
    parameters: {
      query: {
        sort_order: number;
      };
      path: {
        category_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Target */
  get_target_categories__category_id__target_get: {
    parameters: {
      path: {
        category_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryTargetResponse"] | null;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upsert Target */
  upsert_target_categories__category_id__target_put: {
    parameters: {
      path: {
        category_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryTargetUpsert"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryTargetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Target */
  delete_target_categories__category_id__target_delete: {
    parameters: {
      path: {
        category_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Groups */
  list_groups_category_groups_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryGroupWithCategories"][];
        };
      };
    };
  };
  /** Create Group */
  create_group_category_groups_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryGroupCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CategoryGroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Group
   * @description Delete a group only if it has no categories.
   * If it has categories, archive it (is_hidden=True) instead.
   */
  delete_group_category_groups__group_id__delete: {
    parameters: {
      path: {
        group_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Group */
  update_group_category_groups__group_id__patch: {
    parameters: {
      path: {
        group_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryGroupUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryGroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Sort Group */
  sort_group_category_groups__group_id__sort_patch: {
    parameters: {
      query: {
        sort_order: number;
      };
      path: {
        group_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CategoryGroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List nudges
   * @description Returns the user's nudges sorted by creation time (newest first).
   * Undismissed nudges always sort before dismissed ones.
   *
   * unread_count: delivered nudges not yet opened and not dismissed.
   */
  list_nudges_nudges_get: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        include_dismissed?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get nudge settings */
  get_settings_nudges_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeSettingsResponse"];
        };
      };
    };
  };
  /** Update nudge settings */
  update_settings_nudges_settings_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NudgeSettingsUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeSettingsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get a single nudge */
  get_nudge_nudges__nudge_id__get: {
    parameters: {
      path: {
        nudge_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete a nudge */
  delete_nudge_nudges__nudge_id__delete: {
    parameters: {
      path: {
        nudge_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Mark nudge as opened */
  open_nudge_nudges__nudge_id__open_post: {
    parameters: {
      path: {
        nudge_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Dismiss a nudge */
  dismiss_nudge_nudges__nudge_id__dismiss_post: {
    parameters: {
      path: {
        nudge_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Mark all nudges as opened */
  mark_all_read_nudges_mark_all_read_post: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /**
   * Register push notification token
   * @description Store the device's push token so the backend can deliver push notifications.
   *
   * Accepts:
   *   - Expo push tokens: "ExponentPushToken[xxxxxx]"  (development + Expo Go)
   *
   * Idempotent — re-registering the same token is safe.
   */
  register_device_nudges_register_device_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDeviceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create a synthetic nudge for testing
   * @description Creates a realistic synthetic nudge for the given trigger_type. Bypasses fatigue and dedup checks. Safe in all environments.
   */
  test_trigger_nudges_test_trigger_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestTriggerRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NudgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Pull
   * @description Return all records created or updated since last_pulled_at.
   * Runs lazy recurring-transaction generation before querying.
   * Scoped to the authenticated user.
   */
  pull_sync_pull_get: {
    parameters: {
      query?: {
        /** @description Unix millisecond timestamp of last successful pull */
        last_pulled_at?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Push
   * @description Process client-side writes for all six WatermelonDB tables.
   * Rate-limited to 60 pushes per user per minute.
   */
  push_sync_push_post: {
    parameters: {
      query?: {
        /** @description Unix millisecond timestamp of last successful pull */
        last_pulled_at?: number;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Bank Alert Webhook
   * @description Receives parsed bank-alert emails forwarded by the Cloudflare email-worker.
   *
   * Security: constant-time comparison against BANK_ALERT_WEBHOOK_SECRET.
   * The endpoint returns 403 (not 401) to avoid leaking auth scheme details.
   *
   * Payload shape (set by the email-worker):
   *     { "to": str, "from": str, "subject": str|null, "body": str|null, "html": str|null }
   *
   * Processing pipeline:
   *     1. Verify shared secret.
   *     2. Parse body → ParsedBankAlert.
   *     3. Resolve recipient username → User.
   *     4. Resolve institution → BankAccount.
   *     5. Deduplicate via external_ref.
   *     6. Insert Transaction row.
   *     7. Update BankAccount.last_synced_at.
   *     8. Enqueue categorize_transactions Celery task.
   *     9. Notify user via WebSocket.
   */
  bank_alert_webhook_webhooks_bank_alerts_post: {
    parameters: {
      header?: {
        "x-monimata-secret"?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Rules
   * @description Return all active recurring rules for the current user.
   */
  list_rules_recurring_rules_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecurringRuleResponse"][];
        };
      };
    };
  };
  /**
   * Create Rule
   * @description Create a new recurring rule. The first occurrence is generated lazily on the next sync.
   */
  create_rule_recurring_rules_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecurringRuleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["RecurringRuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Rule */
  get_rule_recurring_rules__rule_id__get: {
    parameters: {
      path: {
        rule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecurringRuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Rule
   * @description Hard-delete a recurring rule. Past transactions generated by this rule are preserved.
   */
  delete_rule_recurring_rules__rule_id__delete: {
    parameters: {
      path: {
        rule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Rule
   * @description Update is_active, ends_on, or next_due. Set is_active=false to pause / stop the rule.
   */
  update_rule_recurring_rules__rule_id__patch: {
    parameters: {
      path: {
        rule_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecurringRuleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecurringRuleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
